# Generated by Django 2.2.3 on 2019-07-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=140, null=True)),
                ('file', models.FileField(upload_to='files/')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
