# Generated by Django 2.2.2 on 2019-06-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemanual',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
