# Generated by Django 2.2.2 on 2019-06-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContentPages', '0002_auto_20190613_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemanual',
            name='name',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
