# Generated by Django 2.2.2 on 2019-06-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('key', models.TextField(null=True)),
                ('nickname', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('state_prov', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('postalcode', models.TextField(null=True)),
                ('website', models.TextField(null=True)),
                ('rookieyear', models.IntegerField(null=True)),
                ('motto', models.TextField(null=True)),
            ],
        ),
    ]
