# Generated by Django 2.2.2 on 2019-06-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('number', models.IntegerField()),
                ('nickname', models.TextField()),
                ('name', models.TextField()),
                ('city', models.TextField()),
                ('state_prov', models.TextField()),
                ('country', models.TextField()),
                ('address', models.TextField()),
                ('postalcode', models.TextField()),
                ('website', models.TextField()),
                ('rookieyear', models.IntegerField()),
                ('motto', models.TextField()),
                ('logo', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
