# Generated by Django 2.2.3 on 2019-07-14 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlueAlliance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='local_event',
        ),
        migrations.DeleteModel(
            name='local_team',
        ),
    ]
