# Generated by Django 2.2.2 on 2019-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlueAlliance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
        migrations.AlterField(
            model_name='team',
            name='key',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
