# Generated by Django 2.2.2 on 2019-06-30 16:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlueAlliance', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='webcasts',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
