# Generated by Django 2.2.2 on 2019-06-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlueAlliance', '0002_auto_20190625_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='key',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
