# Generated by Django 2.2.2 on 2019-06-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlueAlliance', '0003_auto_20190625_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='key',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='motto',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='nickname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='postalcode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='rookieyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='state_prov',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='website',
            field=models.TextField(null=True),
        ),
    ]
