# Generated by Django 2.2.2 on 2019-06-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlueAlliance', '0003_auto_20190630_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='webcasts',
            field=models.TextField(null=True),
        ),
    ]
