# Generated by Django 2.2.2 on 2019-07-01 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlueAlliance', '0004_auto_20190630_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='number',
            new_name='team_number',
        ),
    ]
