# Generated by Django 2.2.2 on 2019-07-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlueAlliance', '0005_auto_20190630_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='postalcode',
            new_name='postal_code',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='rookieyear',
            new_name='rookie_year',
        ),
        migrations.AddField(
            model_name='team',
            name='location_name',
            field=models.TextField(null=True),
        ),
    ]
