# Generated by Django 2.2.2 on 2019-07-01 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlueAlliance', '0006_auto_20190630_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
