# Generated by Django 2.2.2 on 2019-07-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TheBlueAlliance', '0007_auto_20190630_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='local_event',
            fields=[
                ('address', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('district', models.TextField(null=True)),
                ('division_keys', models.TextField(null=True)),
                ('end_date', models.TextField(null=True)),
                ('event_code', models.TextField(null=True)),
                ('event_type', models.IntegerField(null=True)),
                ('event_type_string', models.TextField(null=True)),
                ('first_event_code', models.TextField(null=True)),
                ('first_event_id', models.TextField(null=True)),
                ('gmaps_place_id', models.TextField(null=True)),
                ('gmaps_url', models.URLField(null=True)),
                ('key', models.TextField(primary_key=True, serialize=False)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('location_name', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('parent_event_key', models.TextField(null=True)),
                ('playoff_type', models.TextField(null=True)),
                ('playoff_type_string', models.TextField(null=True)),
                ('postal_code', models.TextField(null=True)),
                ('short_name', models.TextField(null=True)),
                ('start_date', models.TextField(null=True)),
                ('state_prov', models.TextField(null=True)),
                ('timezone', models.TextField(null=True)),
                ('webcasts', models.TextField(null=True)),
                ('website', models.URLField(null=True)),
                ('week', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
            ],
        ),
    ]
