# Generated by Django 2.2.2 on 2019-07-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TheBlueAlliance', '0008_local_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='local_team',
            fields=[
                ('address', models.TextField(null=True)),
                ('city', models.TextField(null=True)),
                ('country', models.TextField(null=True)),
                ('gmaps_place_id', models.TextField(null=True)),
                ('gmaps_url', models.URLField(null=True)),
                ('key', models.TextField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lng', models.FloatField(null=True)),
                ('location_name', models.TextField(null=True)),
                ('motto', models.TextField(null=True)),
                ('name', models.TextField(null=True)),
                ('nickname', models.TextField(null=True)),
                ('postal_code', models.TextField(null=True)),
                ('rookie_year', models.IntegerField(null=True)),
                ('state_prov', models.TextField(null=True)),
                ('team_number', models.IntegerField(primary_key=True, serialize=False)),
                ('website', models.URLField(null=True)),
            ],
        ),
    ]
