# Generated by Django 2.2.2 on 2019-07-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting', '0002_auto_20190703_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='stronghold_match',
            name='blue_foul',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stronghold_match',
            name='highgoal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stronghold_match',
            name='lowgoal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stronghold_match',
            name='reach_defence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stronghold_match',
            name='red_foul',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stronghold_match',
            name='blue_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stronghold_match',
            name='driver_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stronghold_match',
            name='red_score',
            field=models.IntegerField(default=0),
        ),
    ]
