# Generated by Django 2.2.2 on 2019-07-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting', '0003_auto_20190703_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stronghold_match',
            old_name='highgoal',
            new_name='highgoals',
        ),
        migrations.RenameField(
            model_name='stronghold_match',
            old_name='lowgoal',
            new_name='lowgoals',
        ),
    ]
