# Generated by Django 2.2.3 on 2019-07-05 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scouting', '0004_auto_20190703_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stronghold_match',
        ),
    ]
