# Generated by Django 2.2.2 on 2019-07-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='team_number',
            field=models.IntegerField(null=True),
        ),
    ]
