# Generated by Django 2.2.2 on 2019-06-27 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactmessage',
            old_name='pub_date',
            new_name='sent_date',
        ),
    ]
