from django.db import models

class Team(models.Model):
    number = models.IntegerField(primary_key=True)
    key = models.TextField(null=True)
    nickname = models.TextField(null=True)
    name = models.TextField(null=True)
    city = models.TextField(null=True)
    state_prov = models.TextField(null=True)
    country = models.TextField(null=True)
    address = models.TextField(null=True)
    postalcode = models.TextField(null=True)
    website = models.TextField(null=True)
    rookieyear = models.IntegerField(null=True)
    motto = models.TextField(null=True)

    def location(self):
        return str("{}, {}, {}".format(city, state_prov, country))

class Event(models.Model):
    address = models.TextField(null=True)
    city = models.TextField(null=True)
    country = models.TextField(null=True)
    district = models.TextField(null=True)
    division_keys = models.TextField(null=True)
    end_date = models.TextField(null=True)
    event_code = models.TextField(null=True)
    event_type = models.IntegerField(null=True)
    event_type_string = models.TextField(null=True)
    first_event_code = models.TextField(null=True)
    first_event_id = models.TextField(null=True)
    gmaps_place_id = models.TextField(null=True)
    gmaps_url = models.URLField(null=True)
    key = models.TextField(primary_key=True)
    lat = models.FloatField(null=True)
    lng = models.FloatField(null=True)
    location_name =models.TextField(null=True)
    name = models.TextField(null=True)
    parent_event_key = models.TextField(null=True)
    playoff_type = models.TextField(null=True)
    playoff_type_string =models.TextField(null=True)
    postal_code = models.TextField(null=True)
    short_name = models.TextField(null=True)
    start_date = models.TextField(null=True)
    state_prov = models.TextField(null=True)
    timezone = models.TextField(null=True)
    webcasts = models.TextField(null=True)
    website = models.URLField(null=True)
    week = models.IntegerField(null=True)
    year = models.IntegerField(null=True)
